Fix git symlinks not working on Windows
The fact that some hyphenation dictionaries are actually sym-linked to other
dictionaries breaks Pyphen on Windows when referring to those symlinks.

Repro sequence on a Win32 machine looks as following:

    >>> import pyphen
    >>> dic = pyphen.Pyphen(lang='en')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "pyphen.py", line 250, in __init__
        hdcache[filename] = HyphDict(filename)
      File "pyphen.py", line 181, in __init__
        self.maxlen = max(len(key) for key in self.patterns)
    ValueError: max() arg is an empty sequence

As per discussion at
http://stackoverflow.com/questions/5917249/git-symlinks-in-windows
which suggests not using symlinks in git repos, implement a pythonic
alternative for language aliases.